### PR TITLE
Feature/op 1360

### PR DESCRIPTION
**Pull request by lruzicki**
Ticket:
https://openimis.atlassian.net/browse/OP-1360

Changes:
- changed 'core_User_Groups' to 'Core_User_Groups' due to conflict with names in Django migrations with "core.user_Groups"
- added missing field for tblPremium

### CODE REVIEW

**Review by delcroip — APPROVED** [review]
@lruzicki  can I merge it or do you want other review / change

**Comment by wzglinieckisoldevelo** [comment]
@delcroip @lruzicki 
There are commits there not present in the develop branch I believe. I think they were added to the main branch as hotfix, and probably should not be added here.

**Comment by lruzicki** [comment]
@delcroip I couldn't rebuild it locally to check if the script is working, could you please check it before merging?

**Comment by lruzicki** [comment]
@delcroip we can merge it

**Pull request merged**
